### ISSUE TITLE
Create yaml file for asymptote

### ISSUE THREAD

**Issue by danleo-ie** [cereda/arara#104]
It's a pleasure to address you, I recently posted a question in [Tex.SE](https://tex.stackexchange.com/q/428580/154390), about the yaml file that I was creating to be able to run the processor for 3d graphics asymptote, thanks to a suggestion from the user @marmot; although the contribution meant adding a -1 to the name of the file, resulting as a solution; What we want is if you could provide a clearer answer on the matter and if the code used contains parts that do not have to do with what you want. I thank you in advance for this tool that allows us to flexibly compile our latex projects.

Here is the attempt:

```
!config
# PDFLaTeX rule for arara
# author: Marco Daniel
# last edited by: xD
# requires arara 3.0+
identifier: asymptote
name: Asymptote
command: <arara> asy @{options} "@{getBasename(file)}-1.asy"
arguments:
- identifier: style
  flag: <arara> @{parameters.style}
  default: asy
- identifier: options
  flag: <arara> @{parameters.options}
```
