### ISSUE TITLE
Integration with Pweave

### ISSUE THREAD

**Issue by mardukbp** [cereda/arara#46]
Following the manual I have this in `~/araraconfig.yaml`

``` yaml
filetypes:
- extension: Plw
  pattern: ^%\\s+
```

`file.Plw` begins with `% arara: pweave` and of course I have a rule called `pweave`.
However, when I execute `arara file` it complains saying "I didn't find any directives in ''file.Plw".

What am I doing wrong? It's so frustrating not being able to enjoy the awesomeness of arara. Thank you!
