### ISSUE TITLE
finished.yaml

### ISSUE THREAD

**Issue by cmhughes** [cereda/arara#69]
Hello to the `arara` team!
Thanks for creating & maintaining such a great tool, it's a vital part of my workflow both at work and at home :)

I'm currently working on a project that has a lot of images, and as a result takes quite a long time to produce a `pdf` (approximately 10 minutes); as such, I like to leave it running in the background. Rather than checking it regularly, I thought that I would create a little 'pop up' rule that tells me when it has finished. As such, I have the following (the following demonstrates a Windows implementation):

```
% arara: latex
% arara: latex
% arara: dvips
% arara: ps2pdf
% arara: finished
```
where `finished.yaml` looks like this:

```YAML
!config
# long tasks can run in the background;
# this rule launches the finished.bat file
# which should bring up a DOS prompt
# author: Chris Hughes
# requires arara 3.0+
#
# Sample usage
#
# % arara: finished
#
identifier: finished
name: finished
commands: 
- <arara> cmd /c start cmd /C finished.bat @{file}
arguments: [] 
```

and `finished.bat` contains

```Batchfile
echo off
REM This is a small file to help me when compiling large 
REM LaTeX documents, e.g the MST125 units; it is called 
REM arara using the finished.yaml rule. It simply brings 
REM a DOS prompt to the front of my screen telling me it is
REM finished.
REM This saves me from having to watch it
title finished! %1
For /f "tokens=1-3 delims=/ " %%a in ('date /t') do (set mydate=%%b-%%a-%%c)
For /f "tokens=1-2 delims=/:" %%a in ("%TIME%") do (set mytime=%%a.%%b)
echo finished working on %1
echo 
for /l %%i in (1,1,3) do echo time stamp: %mytime%, %mydate%
pause
```

I don't think my implementation is ideal/optimal, but I wondered if it might inspire a better/more robust idea from the `arara` development team?

Chris :)

PS: this isn't really an issue, but I wasn't sure where it would best be placed...

**Comment by cereda** [comment]
Hello, Chris! :smiley: 

I have good and bad news.

**Good news:** it is, in fact, quite straightforward to make `arara` trigger a message box using Java's `JOptionPane`. Something along these lines would do the trick:

```yaml
!config
identifier: finished
name: finished
commands: 
- <arara> @{ javax.swing.JOptionPane.showMessageDialog(null, "Yay, arara has finished the job!"); "" }
arguments: [] 
```

As `showMessageDialog` does not return any values, I have to force the evaluation to bring an empty string in the end as result, but it is just a technical detail, do not worry with it. :smiley: 

When running this rule, you will get a lovely message box:

![message](https://cloud.githubusercontent.com/assets/302062/8186636/c3257fda-1421-11e5-8b4a-8948c0fcd22a.png)

*I haven't included the code calling the Swing UI manager to use the system look and feel, that's why this message box does not look so nice, but it does the job.*

**Bad news:** The message box will appear before `arara` effectively runs any system command. This is a nuisance changed in the upcoming `4.0` branch; older versions evaluate expressions beforehand, then runs the resulting commands as a batch. From `4.0` on, each rule is evaluated and executed on the fly, which is, to some extent, along the lines of a REPL concept (read, eval, print, loop).

Sadly, there's no way of changing this behaviour in the current version of `arara`, but our upcoming version already solves this problem. For comparison, here's the very same rule ported to the new format (amongst other options of the new format):

```yaml
!config
identifier: notify
name: Notify
authors:
- Chris Hughes
- Paulo Cereda
commands:
- name: User notification
  command: >
    @{
        javax.swing.JOptionPane.showMessageDialog(null, "Yay, arara has finished the job!");
        return true;
    }
arguments: []
```

*I took the liberty of changing the rule name.*

My test file is as follows (it calls the TeX engine and the notification):

```latex
% arara: tex
% arara: notify
Hello world!
\bye
```

When running `4.0`, I get the following output:

![message](https://cloud.githubusercontent.com/assets/302062/8187097/754d93b2-1424-11e5-9a2b-868b5886d526.png)

As expected. :smiley: When clicking the `OK` button, we have the final output:

![message](https://cloud.githubusercontent.com/assets/302062/8187122/95480fe4-1424-11e5-9602-c4557237e83f.png)

There we go.

Sadly, there's nothing much I could do with the current version. :cry: Thankfully, I am working pretty hard on the user manual (expect a huge list of improvements, corrections and features), so the new version will finally shine and you will be able to do wonderful things once again. :smiley: 

**Message to the team:** *(Chris, you are also part of the team, by the way)* How do you like the idea of including a couple of UI methods to the rule context? Like the one Chris wants to use in this example. Maybe just one generic message box, where you can specify title, message body, width and type of message (information, error, warning, etc). To the [Gitter chatroom](https://gitter.im/cereda/arara), boys and girls! :smile: 

All the best!

Paulo
