### ISSUE TITLE
Update to the indent.yaml rule

### ISSUE THREAD

**Issue by cmhughes** [cereda/arara#77]
Hello `arara` team :)
Thanks for your continued work on this excellent tool!

I'm working on a new version of `latexindent.pl` and have a few things that I'd like to modify to the `indent.yaml` rule (https://github.com/cereda/arara/blob/master/rules/indent.yaml). 

In particular, regarding the `localSettings` feature of `latexindent.pl` can be called in the following way (note the optional parameter to the `-l` switch):

`latexindent -l myfile.tex`

`latexindent -l=myyaml.yaml myfile.tex`

What would be the best way to update the rule? It looks like the syntax has changed a little since I last looked at `arara`. 

Many thanks for your time.
Best
Chris (cmhughes)

`

**Comment by cereda** [comment]
Hi Chris!

Sorry for the delay in replying to you, I am in a hurry in the last few days. :watch: 

I have a couple of ideas, but it's been a while. :smile: I will write some tests and report back.

Thank you!

**Comment by cereda** [comment]
Hi Chris!

I updated the `indent.yaml` rule as follows:

```yaml
!config
# Arara, the cool TeX automation tool
# Copyright (c) 2012, Paulo Roberto Massa Cereda 
# All rights reserved.
#
# This rule is part of arara.
identifier: indent
name: Indent
authors:
- Chris Hughes
- Paulo Cereda
commands:
- name: The latexindent.pl script
  command: >
    @{
        return getCommand('latexindent', silent, trace, settings, cruft, overwrite, output, file);
    }
arguments:
- identifier: silent
  flag: "@{isTrue(parameters.silent, '-s')}"
- identifier: overwrite
  flag: "@{isTrue(parameters.overwrite, '-w')}"
- identifier: trace
  flag: "@{isTrue(parameters.trace, '-t')}"
- identifier: settings
  flag: >
    @{
      check = parameters.containsKey('where');
      location = check ? parameters.where : '';
      if ([ 'local', 'onlydefault' ].contains(parameters.settings)) {
          return isTrue(parameters.settings == 'local', isTrue(check, '-l='.concat(location), '-l'), '-d');
      }
      else {
          throwError('You provided an invalid value for settings.');
      }
    }
- identifier: cruft
  flag: "-c=@{parameters.cruft}"
- identifier: output
  flag: "@{[ '-o', parameters.output ]}"
- identifier: where
  flag: >
    @{
      check = parameters.containsKey('settings');
      setting = check ? parameters.settings : '';
      if (setting != 'local') {
          throwError('This key requires a local setting.');
      }
    }
```

The `settings` parameter behaves the same, but it has an additional check for an optional `where` parameter. The latter cannot exist without the former, as `arara` will complain. Let us check some examples:

```tex
% arara: indent: { settings: local }
Hello world.
\bye
```

```bash
[paulo@cambridge arara] $ java -jar a4.jar -n test.tex 
  __ _ _ __ __ _ _ __ __ _ 
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing 'test.tex' (size: 55 bytes, last modified: 01/13/2016
18:00:54), please wait.

[DR] (Indent) The latexindent.pl script
-----------------------------------------------------------------
Authors: Chris Hughes, Paulo Cereda
About to run: [ latexindent, -l, test.tex ]

Total: 0.12 seconds
```

```tex
% arara: indent: { settings: local, where: /home/paulo }
Hello world.
\bye
```

```bash
[paulo@cambridge arara] $ java -jar a4.jar -n test.tex 
  __ _ _ __ __ _ _ __ __ _ 
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing 'test.tex' (size: 75 bytes, last modified: 01/13/2016
18:22:11), please wait.

[DR] (Indent) The latexindent.pl script
-----------------------------------------------------------------
Authors: Chris Hughes, Paulo Cereda
About to run: [ latexindent, -l=/home/paulo, test.tex ]

Total: 0.11 seconds
```

```tex
% arara: indent: { settings: onlydefault, where: /home/paulo }
Hello world.
\bye
```

```bash
[paulo@cambridge arara] $ java -jar a4.jar -n test.tex 
  __ _ _ __ __ _ _ __ __ _ 
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing 'test.tex' (size: 81 bytes, last modified: 01/13/2016
18:23:28), please wait.

I have spotted an error in rule 'indent' located at
'/home/paulo/Diversos/Testes/arara/rules'. I could not evaluate
the flag expression of one of the arguments. This part is quite
tricky, since it involves aspects of the underlying expression
language. I will do my best to help you in any way I can. There
are more details available on this exception:

DETAILS ---------------------------------------------------------
[Error: throwError('This key requires a local setting.'): This
key requires a local setting.]
[Near : {... @{ ....}]
           
 ^
[Line: 1, Column: 1]

Total: 0.12 seconds
```

```tex
% arara: indent: { where: /home/paulo }
Hello world.
\bye
```

```bash
[paulo@cambridge arara] $ java -jar a4.jar -n test.tex 
  __ _ _ __ __ _ _ __ __ _ 
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing 'test.tex' (size: 58 bytes, last modified: 01/13/2016
18:24:09), please wait.

I have spotted an error in rule 'indent' located at
'/home/paulo/Diversos/Testes/arara/rules'. I could not evaluate
the flag expression of one of the arguments. This part is quite
tricky, since it involves aspects of the underlying expression
language. I will do my best to help you in any way I can. There
are more details available on this exception:

DETAILS ---------------------------------------------------------
[Error: throwError('This key requires a local setting.'): This
key requires a local setting.]
[Near : {... @{ ....}]
           
 ^
[Line: 1, Column: 1]

Total: 0.10 seconds
```

The error message could be better rephrased, so I leave the honour to you. :wink: 

How do you like my approach? If you agree with it, I can commit this new rule as soon as possible.

All the best!

Paulo
