### ISSUE TITLE
Summarising rule

### ISSUE THREAD

**Issue by samcarter8** [cereda/arara#81]
Thank you so much for creating this fantastic tool! This saves so much time!

A small feature request: I'd like to create a new rule (or modify an existing) to summarise all the compilation steps at the end. In principal arara already does this by printing 

```
(PDFLaTeX) PDFLaTeX engine
(Biber) The Biber reference management software
(PDFLaTeX) PDFLaTeX engine
(PDFLaTeX) PDFLaTeX engine
```
but when using `arara --verbose` to see the log file, these messages are hidden in between. What I would like to do is print them at the end of `arara` when the total elapsed time gets displayed. Is this somehow possible? 

In case it makes a difference, I am using `arara 4.0` (could not wait to play with all these nice toys :)

**Comment by cereda** [comment]
Hello! :wink: 

Thanks for the kind words!

To be honest, I am quite reticent to add new features now, specially when version 4.0 is not even officially released. I need to take a look at my code and see if there's a way to include this feature without significant changes in the underlying engine. I will report back when I have a more reliable coverage. :wink: 

There's a way to achieve something along those lines without dissecting the bowels of this parrot (as to amuse John Cleese, it's not dead). Version 4.0 has something called *session*, in which you can use it to exchange data from rule to rule. The default behaviour is to provide hermetic rules, that is, rules that are sealed, encapsulated (what happens in Vegas, stay in Vegas). However, there's a rule method named `getSession()` in which we can manipulate persistent data, in the sense of keeping awareness after the rule pines for the fjords.

Here's a modified `pdftex.yaml` rule:

```yaml
- name: PDFTeX engine
  command: >
    @{
        if (!getSession().exists('tasks')) {
            getSession().insert('tasks',[]);
        }
        getSession().obtain('tasks').add('I just ran PDFTeX on ' + file);
        return getCommand('pdftex', interaction, draft, shell, synctex, options, file)
    }
```

The first conditional is required to initialize the `tasks` entry (think of a session as a map, in which you put and retrieve things based on an key). The line after the conditional adds the reference to what's being done at the moment.

Now, let us write a `summarize.yaml` rule:

```yaml
!config
identifier: summarize
name: Summarize
authors:
- Paulo Cereda
commands:
- name: Summarizes the execution
  command: >
    @{
        if (!getSession().exists('tasks')) {
            getSession().insert('tasks',[]);
        }
        tasks = getSession().obtain('tasks');
        text = 'These are the tasks arara ran in a couple of seconds ago:<br/>';
        foreach (task : tasks) {
            text = text + '- ' + task + '<br/>';
        }
        showMessage(2, 'Summary', text);
        return true;
     }
arguments: []
```

The idea here is to get the current execution and display in a message box (another feature of version 4.0). It's possible to use a common Java output method to print the message to the terminal, but it will mess the layout greatly (or maybe it's just my OCD being triggered). A sample test file:

```tex
% arara: pdftex
% arara: pdftex
% arara: summarize
Hello world!
\bye
```

And the execution:

![Quack!](https://cloud.githubusercontent.com/assets/302062/18107935/710529f6-6ee0-11e6-82b7-b68cf1410782.png)

Another approach is to use one of the internal libraries used by `arara` and write the data to a separate `.log` file. Let us check a modified `summarize.yaml`:

```yaml
!config
# Arara, the cool TeX automation tool
# Copyright (c) 2012, Paulo Roberto Massa Cereda 
# All rights reserved.
#
# This rule is part of arara.
identifier: summarize
name: Summarize
authors:
- Paulo Cereda
commands:
- name: Summarizes the execution
  command: >
    @{
        if (!getSession().exists('tasks')) {
            getSession().insert('tasks',[]);
        }
        tasks = getSession().obtain('tasks');
        org.apache.commons.io.FileUtils.writeLines(new java.io.File('execution.log'), tasks);
        return true;
     }
arguments: []
```

When running `arara`:

```
[paulo@cambridge target] $ java -jar arara.jar test.tex 
  __ _ _ __ __ _ _ __ __ _ 
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing 'test.tex' (size: 70 bytes, last modified: 08/30/2016
17:55:27), please wait.

(PDFTeX) PDFTeX engine .................................. SUCCESS
(PDFTeX) PDFTeX engine .................................. SUCCESS
(Summarize) Summarizes the execution .................... SUCCESS

Total: 0.47 seconds
[paulo@cambridge target] $ cat execution.log 
I just ran PDFTeX on test.tex
I just ran PDFTeX on test.tex
```

It's not exactly what you want, but we are half way there. :wink: 

Cheerio!
