### ISSUE TITLE
'indent' task has a YAML syntax error

### ISSUE THREAD

**Issue by EngCat** [cereda/arara#88]
Hello arara team :)
Thanks for your excellent work!

I have had an issue with **indend rule** on my macbook (running Sierra and TeXLive 2016), while **latexindent** works fine. This is log file
```
09 Mar 2017 11:00:59.644 INFO  Arara - Welcome to arara!
09 Mar 2017 11:00:59.648 INFO  Arara - Processing file 'test.tex', please wait.
09 Mar 2017 11:00:59.649 INFO  DirectiveExtractor - Reading directives from test.tex.
09 Mar 2017 11:00:59.650 TRACE DirectiveExtractor - Directive found in line 3 with pdflatex.
09 Mar 2017 11:00:59.651 TRACE DirectiveExtractor - Directive found in line 4 with indent.
09 Mar 2017 11:00:59.652 TRACE DirectiveExtractor - Directive found in line 5 with indent: {overwrite: yes}.
09 Mar 2017 11:00:59.655 TRACE DirectiveExtractor - Directive found in line 6 with indent: {output: myfile.tex}.
09 Mar 2017 11:00:59.656 TRACE DirectiveExtractor - Directive found in line 7 with indent: {silent: yes}.
09 Mar 2017 11:00:59.657 TRACE DirectiveExtractor - Directive found in line 8 with indent: {trace: yes}.
09 Mar 2017 11:00:59.658 TRACE DirectiveExtractor - Directive found in line 9 with indent: {localSettings: yes}.
09 Mar 2017 11:00:59.659 TRACE DirectiveExtractor - Directive found in line 10 with indent: {onlyDefault: on}.
09 Mar 2017 11:00:59.663 INFO  DirectiveParser - Parsing directives.
09 Mar 2017 11:00:59.667 INFO  TaskDeployer - Deploying tasks into commands.
09 Mar 2017 11:00:59.667 TRACE TaskDeployer - Task 'pdflatex' found in '/usr/local/texlive/2016/texmf-dist/scripts/arara/rules'.
09 Mar 2017 11:00:59.683 TRACE TaskDeployer - Task 'indent' found in '/Users/***/arara_rules'.
09 Mar 2017 11:00:59.690 ERROR Arara - Arara raised an exception with the following message:
09 Mar 2017 11:00:59.690 ERROR Arara - It appears that the 'indent' task has a YAML syntax error or an invalid field. Could you take a look at the 'indent.yaml' file located at '/Users/***/arara_rules'. I tried my best to dump the error message, so here it is:

Problem: Can't construct a java object for tag:yaml.org,2002:com.github.arara.model.AraraRuleConfig; exception=Cannot create property=authors for JavaBean=com.github.arara.model.AraraRuleConfig@6ee52dcd; Unable to find property 'authors' on class: com.github.arara.model.AraraRuleConfig
Error found in line 0, column 0.
    !config
    ^

```
It's a local rule because I didn't find **indent.yaml** in TeXLive 2016.
Java version is "1.8.0_101" and I'm only a LaTeX user. Could anyone help me?

**Comment by cereda** [comment]
Hello, friend!

Thanks for the report! It might be a wild guess, but I believe I know what is going on. :wink:

The `.log` template is surely from `arara` 3.0, the one shipped with TeX Live, and the error raised seems to indicate an unknown property named `authors`. This property was introduced in version 4.0, the one currently featured in this repository, and it's not backwards compatible. When `arara` 4.0 is out (hopefully, when my thesis is done, and it is getting close!), we will need to port old rules to the new format.

The solution here is to backport the `indent` rule to version 3.0, so everything is correctly understood. Where did you get the `indent` rule? From here? If so, I can write a 3.0 version of it for you. If you copied elsewhere, could you please post it here?

Thanks again for letting me know and sorry for the potential inconveniences this issue had caused to you.

All the best, pal!

Paulo

**Comment by EngCat** [comment]
Thanks for your quick reply!

> Where did you get the indent rule? From here?

Yes, I followed the link in `latexindent` guide shipped with TeX Live.

**Comment by nlct** [comment]
We also need to take into account the change in `latexindent`'s syntax (see [Updates to indent.yaml #87](https://github.com/cereda/arara/issues/87)), so the rule also depends on the `latexindent` version.

The following works with `arara` v4.0 and `latexindent` version 2.1R:
```latex
% arara: indent: {overwrite: yes, silent: yes,  trace: yes, settings: onlydefault}
\documentclass{article}

\begin{document}

\begin{itemize}
\item Sample
\end{itemize}

\end{document}
```

**Comment by EngCat** [comment]
So, the best way seems to be shipping the rule with TeXLive...

**Comment by cereda** [comment]
That is the plan, actually. 😉 

For version 4.0, this new rule will be included. For version 3.0, we might need a backport. And as @nlct mentioned, we need to know the `latexindent` version.

**Comment by EngCat** [comment]
Got it. I've upgraded to `latexindent` 3.0

**Comment by cereda** [comment]
Without testing:

```yaml
!config
identifier: indent
name: Indent
command: 'latexindent @{silent} @{trace} @{settings} @{cruft} @{overwrite} @{output} @{file}'
arguments:
- identifier: silent
  flag: "@{isTrue(parameters.silent, '-s')}"
- identifier: overwrite
  flag: "@{isTrue(parameters.overwrite, '-w')}"
- identifier: trace
  flag: "@{isTrue(parameters.trace, '-t')}"
- identifier: settings
  flag: >
    @{
      check = parameters.containsKey('where');
      location = check ? parameters.where : '';
      if ([ 'local', 'onlydefault' ].contains(parameters.settings)) {
          return isTrue(parameters.settings == 'local', isTrue(check, '-l='.concat(location), '-l'), '-d');
      }
    }
- identifier: cruft
  flag: "-c=@{parameters.cruft}"
- identifier: output
  flag: "@{[ '-o', parameters.output ]}"
- identifier: where
  flag: >
    @{
      check = parameters.containsKey('settings');
      setting = check ? parameters.settings : '';
    }
```

Could you try this rule?
