### ISSUE TITLE
Specify rules in external YAML file

### ISSUE THREAD

**Issue by tobiasdiez** [cereda/arara#97]
It would be nice to specify the build rules not in the `.tex` file but in an external `.yml`. For example:
````yml
fileA.tex:
   - pdflatex
   - bibtex
   - pdflatex:
      option
   - pdflatex
fileB.tex:
   - lualatex
   - biber
   - lualatex
   - lualatex
````
Personally, I don't like to mix build information with the content of the tex file (and some coauthors/text editors are very particular about the first lines). Moreover, this external configuration file has advantages when external files (like tikz pictures) have to compiled as dependencies. Finally, with such an feature arara could be used as a perfect build tool (i.e, compile multiple files and projects including all their dependencies).

Thanks for your work on arara!
